# Generated by Django 5.1.5 on 2025-04-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coustomer_details',
            name='category',
            field=models.CharField(choices=[('WORK', 'Work'), ('HOME', 'Home')], max_length=20),
        ),
    ]
