# Generated by Django 5.1.5 on 2025-04-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_coustomer_details_category_order_placed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coustomer_details',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order_placed',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Packed', 'Packed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancled', 'Cancled')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Packed', 'Packed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancled', 'Cancled')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PIANO', 'Piano'), ('E_GUITER', 'E_Guiter'), ('A_Guiter', 'A_Guiter'), ('KEY_BOARD', 'Key_Board'), ('FLUTE', 'FLUTE'), ('VIOLIN', 'Violin'), ('DRUMS', 'Drums'), ('TRUMPETS', 'TRUMPETS'), ('PADS', 'Pads'), ('SAXOPHONE', 'Saxophone'), ('SITAR', 'Sitar')], max_length=20),
        ),
    ]
