# Generated by Django 5.1.5 on 2025-04-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_coustomer_details_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coustomer_details',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
